wandb_version: 1

lr:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704969390.023648
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      - 105
      3:
      - 5
      - 7
      - 13
      - 23
      4: 3.10.13
      5: 0.16.1
      6: 4.36.2
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
